// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./src/components/PaginationBar 2.vue')['default']
    DetailsText: typeof import('./src/components/typography/DetailsText.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConatiner: typeof import('element-plus/es')['ElConatiner']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ErrorOverlay: typeof import('./src/components/common/ErrorOverlay.vue')['default']
    HeadingText: typeof import('./src/components/typography/HeadingText.vue')['default']
    InfoSection: typeof import('./src/components/characters/InfoSection.vue')['default']
    LinkButton: typeof import('./src/components/common/LinkButton.vue')['default']
    LoadingOverlay: typeof import('./src/components/common/LoadingOverlay.vue')['default']
    OrderBySelect: typeof import('./src/components/forms/OrderBySelect.vue')['default']
    PaginationBar: typeof import('./src/components/PaginationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
